### ISSUE TITLE
鼠鼠不会用大佬带带

### ISSUE THREAD

**Issue by YanSGod** [Amorter/henuLibrary#1]
PS C:\Users\YanSGod\Desktop\henuLibrary-main> python.exe .\main.py
Traceback (most recent call last):
  File "C:\Users\YanSGod\Desktop\henuLibrary-main\main.py", line 2, in <module>
    import api
  File "C:\Users\YanSGod\Desktop\henuLibrary-main\api.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Amorter** [comment]
使用pip安装request包
pip install request
